@extends('layouts.app')
@section('title', 'ติดตามคำขอแลกเปลี่ยน')
@section('page-title', 'ติดตามคำขอแลกเปลี่ยน')
@section('content')
    <div class="content-heading"><h1 class="mb-1">ติดตามคำขอแลกเปลี่ยน</h1><p class="text-secondary mb-0">ดูข้อมูลคำขอทั้งหมดแบบอ่านอย่างเดียว</p></div>
    <form method="GET" class="campus-card bg-white admin-filter-panel"><div class="row g-2 align-items-end">
        <div class="col-12 col-lg-4"><label class="form-label" for="request-search">ค้นหา</label><input id="request-search" name="q" value="{{ request('q') }}" class="form-control" placeholder="ชื่อ อีเมล หรือทักษะ"></div>
        <div class="col-12 col-sm-4 col-lg-2"><label class="form-label" for="request-status">สถานะ</label><select id="request-status" name="status" class="form-select"><option value="">ทั้งหมด</option>@foreach($statusLabels as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-6 col-sm-4 col-lg-2"><label class="form-label" for="date-from">ตั้งแต่วันที่</label><input id="date-from" type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div>
        <div class="col-6 col-sm-4 col-lg-2"><label class="form-label" for="date-to">ถึงวันที่</label><input id="date-to" type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div>
        <div class="col-12 col-lg-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1" type="submit"><i class="bi bi-search me-1" aria-hidden="true"></i>ค้นหา</button><a class="btn btn-outline-secondary" href="{{ route('admin.exchange-requests.index') }}" aria-label="ล้างตัวกรอง"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i></a></div>
    </div></form>
    <div class="campus-card bg-white admin-table-panel"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ผู้ส่ง</th><th>ผู้รับ</th><th>ทักษะ</th><th>สถานะ</th><th>วันที่ส่ง</th><th class="text-end">รายละเอียด</th></tr></thead><tbody>
    @forelse($requests as $requestItem)<tr><td class="text-truncate" style="max-width: 150px" title="{{ $requestItem->sender->name }}">{{ $requestItem->sender->name }}</td><td class="text-truncate" style="max-width: 150px" title="{{ $requestItem->receiver->name }}">{{ $requestItem->receiver->name }}</td><td class="text-truncate" style="max-width: 210px" title="{{ $requestItem->senderUserSkill->historicalSkill->name }} → {{ $requestItem->receiverUserSkill->historicalSkill->name }}">{{ $requestItem->senderUserSkill->historicalSkill->name }} → {{ $requestItem->receiverUserSkill->historicalSkill->name }}</td><td><span class="status-badge status-{{ $requestItem->status }}">{{ $statusLabels[$requestItem->status] }}</span></td><td>{{ $requestItem->created_at->format('d/m/Y H:i') }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.exchange-requests.show', $requestItem) }}">ดูรายละเอียด</a></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">ไม่พบคำขอตามเงื่อนไข</td></tr>@endforelse
    </tbody></table></div>@if($requests->hasPages())<div class="mt-3">{{ $requests->links() }}</div>@endif</div>
@endsection
